import {
	Activity03Icon,
	ArrowDown01Icon,
	ArrowRight02Icon,
	ArrowUpRight01Icon,
	Book02Icon,
	Calendar03Icon,
	Call02Icon,
	Cancel01Icon,
	Clock01Icon,
	Dumbbell01Icon,
	Facebook01Icon,
	Fire02Icon,
	InstagramIcon,
	Leaf01Icon,
	Location01Icon,
	Mail01Icon,
	Menu02Icon,
	MinusSignIcon,
	Moon02Icon,
	PlusSignIcon,
	Sun03Icon,
	Target02Icon,
	Tick02Icon,
	UserMultipleIcon,
	WeightScale01Icon,
	WhatsappIcon,
	YoutubeIcon
} from '@hugeicons/core-free-icons';

// One name per purpose, so a glyph swap happens here and nowhere else.
export const icons = {
	'arrow-right': ArrowRight02Icon,
	'arrow-up-right': ArrowUpRight01Icon,
	book: Book02Icon,
	calendar: Calendar03Icon,
	check: Tick02Icon,
	'chevron-down': ArrowDown01Icon,
	clock: Clock01Icon,
	close: Cancel01Icon,
	dumbbell: Dumbbell01Icon,
	flame: Fire02Icon,
	leaf: Leaf01Icon,
	mail: Mail01Icon,
	menu: Menu02Icon,
	minus: MinusSignIcon,
	moon: Moon02Icon,
	phone: Call02Icon,
	pin: Location01Icon,
	plus: PlusSignIcon,
	pulse: Activity03Icon,
	scale: WeightScale01Icon,
	sun: Sun03Icon,
	target: Target02Icon,
	users: UserMultipleIcon,
	facebook: Facebook01Icon,
	instagram: InstagramIcon,
	whatsapp: WhatsappIcon,
	youtube: YoutubeIcon
} as const;

export type IconName = keyof typeof icons;
